export const AUTH_START = 'AUTH_START'
export const AUTH_START_SUCCESS = 'AUTH_START_SUCCESS'
export const AUTH_START_FAILURE = 'AUTH_START_FAILURE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'
